import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });

const sfpro = localFont({
	src: [
		{
			path: "./fonts/SF_Pro.woff2",
			weight: "400",
			style: "normal",
		},
		{
			path: "./fonts/SF_Pro_semibold.woff2",
			weight: "600",
			style: "normal",
		},
		{
			path: "./fonts/SF_Pro_bold.woff2",
			weight: "700",
			style: "normal",
		},
		{
			path: "./fonts/SF_Pro_heavy.woff2",
			weight: "800",
		},
	],
	variable: "--font-sfpro",
});

const ambrose = localFont({
	src: [
		{
			path: "./fonts/UTM-Ambrose.ttf",
			weight: "400",
			style: "normal",
		},
	],
	variable: "--font-ambrose",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sfpro.variable} ${inter.className} ${ambrose.variable} font-sfpro antialiased`}>
				{children}
			</body>
		</html>
	);
}
